# Generated by Django 2.2 on 2019-06-17 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='company', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('embeddingsPath', models.CharField(default='', max_length=200)),
                ('studentsPhotosPath', models.CharField(default='', max_length=200)),
                ('lecturesPhotosPath', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='instructor', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('idfk_company', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='accounts.Company')),
            ],
        ),
    ]
