# Generated by Django 2.2 on 2019-06-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190616_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='idfk_Company',
            new_name='idfk_company',
        ),
    ]
