# Generated by Django 2.2 on 2019-06-03 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190603_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
