# Generated by Django 2.2 on 2019-06-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
