# Generated by Django 2.2 on 2019-06-16 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='idfk_company',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='accounts.Company'),
        ),
        migrations.AlterField(
            model_name='student',
            name='idfk_company',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.Company'),
        ),
    ]
