# Generated by Django 2.2 on 2019-06-03 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('idfk_lecture', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='manager.Lecture')),
                ('idfk_student', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='manager.Student')),
            ],
            options={
                'unique_together': {('idfk_lecture', 'idfk_student')},
            },
        ),
    ]
